### ISSUE TITLE
First try, and plugin fails

### ISSUE THREAD

**Issue by samip5** [julianxhokaxhiu/docker-nginx-reloaded#1]
I pulled it from Docker Hub, and this is the first thing I see.
What's going on here?

```
2020-03-31 05:41:56,454 INFO spawned: 'dynsd' with pid 386
2020-03-31 05:41:56,454 INFO spawned: 'dynsd' with pid 386
[05:41:57] INFO: [CORE] Loading plugin 'dynsdjs-plugin-docker'...
[05:41:57] INFO: [DOCKER] Connected to Docker API...
[05:41:57] INFO: [DNS] Listening on [::]:53/tcp
[05:41:57] INFO: [DNS] Listening on 0.0.0.0:53/udp
[05:41:57] INFO: [DNS] Listening on [::]:53/udp
/usr/lib/node_modules/dynsdjs-plugin-docker/dist/DynsdDocker.js:1
(function(root,factory){'object'==typeof exports&&'object'==typeof module?module.exports=factory():'function'==typeof define&&define.amd?define([],factory):'object'==typeof exports?exports.DynsdDocker=factory():root.DynsdDocker=factory()})('undefined'==typeof self?this:self,function(){var _Mathmax=Math.max,_StringfromCharCode=String.fromCharCode,_Mathceil=Math.ceil,_Mathround=Math.round,_Mathlog=Math.log,_Mathpow=Math.pow,_Mathfloor=Math.floor,_Mathabs=Math.abs,_Mathmin=Math.min;return function(modules){function __webpack_require__(moduleId){if(installedModules[moduleId])return installedModules[moduleId].exports;var module=installedModules[moduleId]={i:moduleId,l:!1,exports:{}};return modules[moduleId].call(module.exports,module,module.exports,__webpack_require__),module.l=!0,module.exports}var installedModules={};return __webpack_require__.m=modules,__webpack_require__.c=installedModules,__webpack_require__.d=function(exports,name,getter){__

TypeError: Cannot read property 'IPAddress' of undefined
    at buildInfo (/usr/lib/node_modules/dynsdjs-plugin-docker/dist/DynsdDocker.js:1:103391)
    at Object.docker.getContainer.inspect [as callback] (/usr/lib/node_modules/dynsdjs-plugin-docker/dist/DynsdDocker.js:1:104455)
    at /usr/lib/node_modules/dynsdjs-plugin-docker/dist/DynsdDocker.js:1:204032
    at Modem.buildPayload (/usr/lib/node_modules/dynsdjs-plugin-docker/dist/DynsdDocker.js:1:133176)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/dynsdjs-plugin-docker/dist/DynsdDocker.js:1:132565)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2020-03-31 05:41:57,431 INFO exited: dynsd (exit status 1; not expected)
2020-03-31 05:41:57,431 INFO exited: dynsd (exit status 1; not expected)
2020-03-31 05:41:58,432 INFO gave up: dynsd entered FATAL state, too many start retries too quickly
2020-03-31 05:41:58,432 INFO gave up: dynsd entered FATAL state, too many start retries too quickly
```

**Comment by samip5** [comment]
@julianxhokaxhiu When was the last time you have updated that/verified that it works?

**Comment by julianxhokaxhiu** [comment]
Sorry, I've seen this only now, not sure why. I'll check this in the next days and let you know.

> When was the last time you have updated that/verified that it works?

It has been a while actually. This is because I didn't catch it personally earlier.

**Comment by julianxhokaxhiu** [comment]
Image has been updated since this issue was created. Feel free to let me know if the issue has been fixed or not. Closing until then, but we can re-open if the issue persists.
